[2025-10-23T18:55:46.440+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-23T18:55:46.492+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag_v5.third_task manual__2025-10-23T18:55:42.773033+00:00 [queued]>
[2025-10-23T18:55:46.516+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag_v5.third_task manual__2025-10-23T18:55:42.773033+00:00 [queued]>
[2025-10-23T18:55:46.521+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 6
[2025-10-23T18:55:46.557+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): third_task> on 2025-10-23 18:55:42.773033+00:00
[2025-10-23T18:55:46.574+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=775) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-23T18:55:46.578+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag_v5', 'third_task', 'manual__2025-10-23T18:55:42.773033+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmpclxll25t']
[2025-10-23T18:55:46.580+0000] {standard_task_runner.py:72} INFO - Started process 778 to run task
[2025-10-23T18:55:46.580+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask third_task
[2025-10-23T18:55:46.743+0000] {task_command.py:467} INFO - Running <TaskInstance: our_first_dag_v5.third_task manual__2025-10-23T18:55:42.773033+00:00 [running]> on host c65f76f8d89c
[2025-10-23T18:55:46.929+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineer' AIRFLOW_CTX_DAG_ID='our_first_dag_v5' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2025-10-23T18:55:42.773033+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-23T18:55:42.773033+00:00'
[2025-10-23T18:55:46.930+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-23T18:55:46.954+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-10-23T18:55:46.957+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hey, I am task3 and will be running after task1 and task2!']
[2025-10-23T18:55:46.989+0000] {subprocess.py:99} INFO - Output:
[2025-10-23T18:55:46.992+0000] {subprocess.py:106} INFO - hey, I am task3 and will be running after task1 and task2!
[2025-10-23T18:55:46.993+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-10-23T18:55:47.061+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-23T18:55:47.063+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=our_first_dag_v5, task_id=third_task, run_id=manual__2025-10-23T18:55:42.773033+00:00, execution_date=20251023T185542, start_date=20251023T185546, end_date=20251023T185547
[2025-10-23T18:55:47.164+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-23T18:55:47.201+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-23T18:55:47.206+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
